# Generated by Django 4.2.2 on 2023-06-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staf',
            new_name='is_staff',
        ),
    ]
