# Generated by Django 4.2.2 on 2023-06-26 22:28

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(blank=True, default='it', max_length=2)),
                ('region', models.CharField(max_length=255, verbose_name='regione')),
                ('province', models.CharField(max_length=255, verbose_name='provincie')),
                ('city', models.CharField(max_length=255, verbose_name='cita')),
                ('zip_code', models.CharField(max_length=5, verbose_name='CAP')),
                ('street_name', models.CharField(max_length=255, verbose_name='via')),
                ('street_number', models.PositiveSmallIntegerField(verbose_name='numero civico')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=core.models.profile_upload_path, verbose_name='location image')),
                ('description', models.TextField(default=None, verbose_name='description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.address')),
            ],
        ),
        migrations.CreateModel(
            name='Orari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='nome giorno settimana')),
                ('start', models.TimeField(verbose_name='ora inizio')),
                ('fine', models.TimeField(verbose_name='ora fine')),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.location', verbose_name='location_schedule')),
            ],
            options={
                'verbose_name': 'orario apertura',
                'verbose_name_plural': 'orari apertura',
            },
        ),
        migrations.AddConstraint(
            model_name='orari',
            constraint=models.UniqueConstraint(fields=('weekday', 'start', 'location'), name='unique_day_start'),
        ),
        migrations.AlterIndexTogether(
            name='orari',
            index_together={('weekday', 'start')},
        ),
    ]
